floor_plane:
  normal:
  - -0.026409462801027322
  - -0.03890360048228307
  - 0.9988939133582083
  point_on_plane:
  - 0
  - 0
  - !!python/object/apply:numpy._core.multiarray.scalar
    - !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      MgtDLcU0DEA=
